"""empty message

Revision ID: 8f0d91a95ffc
Revises: 
Create Date: 2017-06-19 15:44:59.114513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0d91a95ffc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfrcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cfr', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfrcodes_cfr'), 'cfrcodes', ['cfr'], unique=False)
    op.create_table('componentcauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cause_code', sa.String(length=1), nullable=True),
    sa.Column('cause_name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eiiscomponenttypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eiis_code', sa.String(length=6), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket', sa.String(), nullable=True),
    sa.Column('facility_name', sa.String(), nullable=True),
    sa.Column('facility_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_docket'), 'facilities', ['docket'], unique=False)
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eiis_code', sa.String(length=4), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systems_eiis_code'), 'systems', ['eiis_code'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('eiiscomponenttype_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('inpo_device_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eiiscomponenttype_id'], ['eiiscomponenttypes.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('lers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('ler_number', sa.String(length=64), nullable=True),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.Column('operating_mode', sa.String(length=3), nullable=True),
    sa.Column('power_level', sa.Integer(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('supplement_expected', sa.Boolean(), nullable=True),
    sa.Column('supplement_date', sa.DateTime(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lers_report_date'), 'lers', ['report_date'], unique=False)
    op.create_table('approves',
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('ler_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ler_id'], ['lers.id'], ),
    sa.PrimaryKeyConstraint('approver_id', 'ler_id')
    )
    op.create_table('cfrselected',
    sa.Column('ler_id', sa.Integer(), nullable=True),
    sa.Column('cfr_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cfr_id'], ['cfrcodes.id'], ),
    sa.ForeignKeyConstraint(['ler_id'], ['lers.id'], )
    )
    op.create_table('componentfailures',
    sa.Column('ler_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('reportable_ices', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['componentcauses.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['ler_id'], ['lers.id'], ),
    sa.PrimaryKeyConstraint('ler_id', 'component_id')
    )
    op.create_table('facilitiesinvolved',
    sa.Column('ler_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['ler_id'], ['lers.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facilitiesinvolved')
    op.drop_table('componentfailures')
    op.drop_table('cfrselected')
    op.drop_table('approves')
    op.drop_index(op.f('ix_lers_report_date'), table_name='lers')
    op.drop_table('lers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('components')
    op.drop_index(op.f('ix_systems_eiis_code'), table_name='systems')
    op.drop_table('systems')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('manufacturers')
    op.drop_index(op.f('ix_facilities_docket'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_table('eiiscomponenttypes')
    op.drop_table('componentcauses')
    op.drop_index(op.f('ix_cfrcodes_cfr'), table_name='cfrcodes')
    op.drop_table('cfrcodes')
    # ### end Alembic commands ###
